version: '3.7'

services:
  zipkin:
    image: openzipkin/zipkin
    hostname: zipkin
    ports:
      - 9411:9411
  grafana:
    image: grafana/grafana
    hostname: grafana
    ports:
      - 3000:3000
