PROFILER:ENABLED = TRUE.
PROFILER:DIRECTORY = ".".
PROFILER:FILE-NAME = "./myProgram.prof".
PROFILER:LISTINGS = FALSE.
PROFILER:DESCRIPTION = "PROFILER".
PROFILER:PROFILING = TRUE.
PROFILER:TRACE-FILTER = "*".

RUN main.p.

PROFILER:ENABLED = FALSE.
PROFILER:PROFILING = FALSE.
PROFILER:WRITE-DATA().

