PROFILER:ENABLED = TRUE.
PROFILER:PROFILING = TRUE.
PROFILER:LISTINGS = FALSE.
PROFILER:DIRECTORY = ".".
PROFILER:FILE-NAME = "./demoProc.prof".
PROFILER:DESCRIPTION = "Running a demo procedure".
PROFILER:TRACE-FILTER = "*".

RUN main.p

PROFILER:ENABLED = FALSE.
PROFILER:PROFILING = FALSE.
PROFILER:WRITE-DATA().

PROCEDURE main:
    RUN procA.
    RUN procB.
END PROCEDURE.

PROCEDURE procA:
    RUN procB.
END PROCEDURE.

PROCEDURE procB:
    RUN procC.
END PROCEDURE.

PROCEDURE procC:
    MESSAGE "This is procedure C".
END PROCEDURE.